# -*- coding: utf-8 -*-
"""spootify.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16sUBwYTSuZIEUBBQNEKyVVmR1k2o8voC

import modul
"""

import spotipy
from spotipy.oauth2 import SpotifyClientCredentials
import pandas as pd
from pymongo import MongoClient
from datetime import datetime
from datetime import timedelta
from airflow import DAG
from airflow.operators.python import PythonOperator
from dotenv import load_dotenv
import os

"""setup spotify API"""

client_id = os.getenv("CLIENT_ID")
client_secret = os.getenv("CLIENT_SECRET")

#authenticate spootify API
client_credentials_manager = SpotifyClientCredentials(client_id=client_id, client_secret=client_secret)
sp = spotipy.Spotify(client_credentials_manager=client_credentials_manager)

